include: package:lint/analysis_options.yaml
# include: package:pedantic/analysis_options.1.11.0.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
